-- Auto-setup SQL script for Constructor CMS
-- This script is generated by quickstart.sh to pre-populate the database
-- with admin user and site settings to skip the web setup wizard.

-- Create admin user
INSERT INTO users (username, email, password, role, created_at, updated_at)
VALUES (
    :admin_username,
    :admin_email,
    :admin_password_hash,
    'admin',
    NOW(),
    NOW()
) ON CONFLICT (email) DO NOTHING;

-- Create site settings
INSERT INTO settings (key, value, created_at, updated_at)
VALUES
    ('site_name', :site_name, NOW(), NOW()),
    ('site_description', :site_description, NOW(), NOW()),
    ('site_url', :site_url, NOW(), NOW()),
    ('site_favicon', '/static/icons/favicon.svg', NOW(), NOW()),
    ('site_logo', '/static/icons/logo.svg', NOW(), NOW()),
    ('site_default_language', 'en', NOW(), NOW()),
    ('setup_complete', 'true', NOW(), NOW())
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW();
