package service

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gorm.io/gorm"

	"constructor-script-backend/internal/models"
	internalservice "constructor-script-backend/internal/service"
)

type stubCourseVideoRepo struct {
	video       models.CourseVideo
	updateCount int
	updateErr   error
}

func (r *stubCourseVideoRepo) Create(video *models.CourseVideo) error { return nil }
func (r *stubCourseVideoRepo) Update(video *models.CourseVideo) error {
	r.updateCount++
	if video != nil {
		copied := *video
		copied.Attachments = append(models.CourseVideoAttachments{}, video.Attachments...)
		r.video = copied
	}
	return r.updateErr
}
func (r *stubCourseVideoRepo) Delete(id uint) error { return nil }
func (r *stubCourseVideoRepo) GetByID(id uint) (*models.CourseVideo, error) {
	if r.video.ID != id {
		return nil, gorm.ErrRecordNotFound
	}
	copy := r.video
	copy.Attachments = append(models.CourseVideoAttachments{}, r.video.Attachments...)
	return &copy, nil
}
func (r *stubCourseVideoRepo) List() ([]models.CourseVideo, error) {
	return []models.CourseVideo{}, nil
}
func (r *stubCourseVideoRepo) Exists(id uint) (bool, error) { return r.video.ID == id, nil }
func (r *stubCourseVideoRepo) GetByIDs(ids []uint) ([]models.CourseVideo, error) {
	return []models.CourseVideo{}, nil
}

func TestVideoServiceUpdateSubtitleReplacesExisting(t *testing.T) {
	uploadDir := t.TempDir()
	uploadSvc := internalservice.NewUploadService(uploadDir)

	repo := &stubCourseVideoRepo{
		video: models.CourseVideo{
			ID:       7,
			Filename: "lesson.mp4",
			Attachments: models.CourseVideoAttachments{
				{Title: "Auto-generated subtitles", URL: "/uploads/lesson-subtitles-old.vtt"},
				{Title: "Worksheet", URL: "/uploads/lesson-notes.pdf"},
			},
		},
	}

	svc := NewVideoService(repo, uploadSvc, nil)

	req := models.UpdateCourseVideoSubtitleRequest{
		Content:       "WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nWelcome\n",
		Title:         "Lesson subtitles",
		AttachmentURL: "/uploads/lesson-subtitles-old.vtt",
	}

	updated, err := svc.UpdateSubtitle(context.Background(), repo.video.ID, req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if repo.updateCount == 0 {
		t.Fatal("expected repository update to be invoked")
	}
	if updated == nil {
		t.Fatal("expected updated video")
	}
	if len(updated.Attachments) != 2 {
		t.Fatalf("expected 2 attachments, got %d", len(updated.Attachments))
	}
	subtitle := updated.Attachments[0]
	if !strings.Contains(subtitle.URL, ".vtt") {
		t.Fatalf("expected subtitle url to point to vtt file, got %q", subtitle.URL)
	}
	if subtitle.URL == "/uploads/lesson-subtitles-old.vtt" {
		t.Fatalf("expected subtitle url to change")
	}
	if subtitle.Title != "Lesson subtitles" {
		t.Fatalf("expected subtitle title to be preserved, got %q", subtitle.Title)
	}
	if updated.Attachments[1].Title != "Worksheet" {
		t.Fatalf("expected secondary attachment to remain, got %q", updated.Attachments[1].Title)
	}

	stored := filepath.Join(uploadDir, filepath.Base(subtitle.URL))
	if _, err := os.Stat(stored); err != nil {
		t.Fatalf("expected subtitle file to exist: %v", err)
	}
}

func TestVideoServiceUpdateSubtitleAddsNewWhenMissing(t *testing.T) {
	uploadDir := t.TempDir()
	uploadSvc := internalservice.NewUploadService(uploadDir)

	repo := &stubCourseVideoRepo{
		video: models.CourseVideo{
			ID:       3,
			Filename: "module.mp4",
			Attachments: models.CourseVideoAttachments{
				{Title: "Guide", URL: "/uploads/module-guide.pdf"},
			},
		},
	}

	svc := NewVideoService(repo, uploadSvc, nil)

	updated, err := svc.UpdateSubtitle(context.Background(), repo.video.ID, models.UpdateCourseVideoSubtitleRequest{
		Content: "WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nHello\n",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(updated.Attachments) != 2 {
		t.Fatalf("expected 2 attachments, got %d", len(updated.Attachments))
	}
	subtitle := updated.Attachments[0]
	if subtitle.Title != autoGeneratedSubtitleTitle {
		t.Fatalf("expected default subtitle title, got %q", subtitle.Title)
	}
	if !strings.HasSuffix(strings.ToLower(subtitle.URL), ".vtt") {
		t.Fatalf("expected subtitle url to end with vtt, got %q", subtitle.URL)
	}
}

func TestVideoServiceUpdateSubtitleRequiresContent(t *testing.T) {
	uploadSvc := internalservice.NewUploadService(t.TempDir())
	repo := &stubCourseVideoRepo{
		video: models.CourseVideo{ID: 9, Filename: "chapter.mp4"},
	}

	svc := NewVideoService(repo, uploadSvc, nil)

	if _, err := svc.UpdateSubtitle(context.Background(), repo.video.ID, models.UpdateCourseVideoSubtitleRequest{Content: "   "}); err == nil {
		t.Fatal("expected validation error for empty subtitle content")
	}
}
